language: node_js

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
    - DATABASE_URL=postgres://postgres@localhost:5433/travis_ci_test

node_js:
  - lts/erbium

before_script:
  - psql -p 5433 -c 'create database travis_ci_test;' -U postgres
