language: node_js

node_js:
  - lts/erbium

addons:
  postgresql: '12'

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
