language: node_js
dist: bionic

env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres

node_js:
  - lts

matrix:
  include:
    - addons:
        postgresql: '9.3'
    - addons:
        postgresql: '9.4'
    - addons:
        postgresql: '9.5'
    - addons:
        postgresql: '9.6'
    - addons:
        postgresql: '10'
    - addons:
        postgresql: '11'
    - addons:
        postgresql: '12'
