language: node_js

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGUSER=postgres PGDATABASE=postgres
    - DATABASE_URL=postgres://postgres@localhost:5433/postgres

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@12-main
  - sleep 1

node_js:
  - lts/erbium
