language: node_js

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGUSER=postgres PGDATABASE=postgres PGPASSWORD=postgres
    - DATABASE_URL=postgres://postgres:postgres@localhost:5433/travis_ci_test

node_js:
  - lts/erbium

before_script:
  - psql -h localhost -p 5433 -c 'create database travis_ci_test;' -U postgres
