language: node_js

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGUSER=postgres PGDATABASE=postgres PGPASSWORD=postgres
    - DATABASE_URL=postgres://postgres:postgres@localhost:5433/postgres

node_js:
  - lts/erbium
